# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d0fd6f02b3e18d9f7ec48b8965e01f7867a968f0cc1ff1a960ff1d4c2307149491817ac7381533d096766661b9418e2a1968e2164264279e41723aa9a4a4b872

test:
  secret_key_base: 22af73ab7e73b2575f035c33c8994da6f6b690b2147309c85f048a573b1f9ac61451109d7c6be1832e57345a925ef8b4cd85260e24af4046d3259362e2082454

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
